### ISSUE TITLE
OS/X: install: illegal option -- T

### ISSUE THREAD

**Issue by david0** [x42/tuna.lv2#3]
In https://github.com/x42/tuna.lv2/blob/master/Makefile#L334 `install` is called with `-T`. I do not know what is the intention behind using this option,  but this option is not supported under OS/X. 

For me everything works fine when removing the `-T`.

**Comment by x42** [comment]
Official universal binaries (http://x42-plugins.com/x42/x42-tuner) are compiled on 10.6.8 with gnu coreutils.

see http://www.gnu.org/software/coreutils/manual/html_node/install-invocation.html#install-invocation for the motivation behind `-T`.

**Comment by david0** [comment]
I haven't expected that, sorry. With coreutils it works fine now. 

It would be nice if you could make the `install` binary name configureable, since its called `ginstall` by default when coreutils is installed using homebrew, but I'm ok with it like it is.

Thank you.

**Comment by x42** [comment]
I'll have to check, I don't recall what the edge case was that motivated `-T`.
